// Maps route paths to their lazy import functions for preloading
export const routePreloadMap: Record<string, () => Promise<any>> = {
  '/': () => import('@/components/DashboardPage'),
  '/chat': () => import('@/components/ChatPage'),
  '/balanca': () => import('@/components/BalancaPage'),
  '/estoque-fisico': () => import('@/components/EstoqueFisicoPage'),
  '/estoque-fiscal': () => import('@/components/EstoqueFiscalPage'),
  '/clientes': () => import('@/components/ClientsPage'),
  '/conta-corrente': () => import('@/components/ContaCorrentePage'),
  '/contas-pagar': () => import('@/components/ContasPagarPage'),
  '/faturamento': () => import('@/components/FaturamentoPage'),
  '/documentos': () => import('@/components/DocumentosPage'),
  '/funcionarios': () => import('@/components/FuncionariosPage'),
  '/epis': () => import('@/components/EPIsPage'),
  '/maquinas': () => import('@/components/MaquinasPage'),
  '/dds': () => import('@/components/DDSPage'),
  '/central-emissao': () => import('@/components/CentralEmissaoPage'),
  '/calculadora-mtr': () => import('@/components/CalculadoraMTRPage'),
  '/relatorios': () => import('@/components/RelatoriosPage'),
  '/usuarios': () => import('@/components/UsersPage'),
  '/auditoria': () => import('@/components/AuditoriaPage'),
  '/configuracoes': () => import('@/components/ConfiguracoesPage'),
};