import { useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { Search, Plus, DollarSign, Download, Wallet, Receipt, MessageCircle } from 'lucide-react';
import { useAutoRefresh } from '@/hooks/useAutoRefresh';
import { RefreshButton } from '@/components/RefreshButton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AvulsosTab } from '@/components/AvulsosTab';

interface ClientRow {
  id: string;
  name: string;
  nickname: string | null;
  document_number: string;
  balance: number;
  phone: string | null;
  whatsapp: string | null;
}

interface LedgerEntry {
  id: string;
  date: string;
  type: 'PESAGEM' | 'PAGAMENTO' | 'VALE' | 'ACERTO';
  mista_kg: number;
  pesada_kg: number;
  limaria_kg: number;
  fundido_kg: number;
  amortecedor_kg: number;
  total_kg: number;
  price: number;
  value: number;       // generated by weighings/vales (positivo aumenta saldo a pagar)
  transferred: number; // pago ao cliente
  notes: string;
}

const money = (v: number) =>
  v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const num = (v: number, d = 2) =>
  v.toLocaleString('pt-BR', { minimumFractionDigits: d, maximumFractionDigits: d });
const fmtDate = (d: string) => new Date(d).toLocaleDateString('pt-BR');
const todayISO = () => new Date().toISOString().slice(0, 10);

const typeBg: Record<LedgerEntry['type'], string> = {
  PESAGEM: 'bg-card',
  PAGAMENTO: 'bg-[#dcfce7]',
  VALE: 'bg-[#ffedd5]',
  ACERTO: 'bg-[#dbeafe]',
};

export function ContaCorrentePage() {
  const { user } = useAuth();
  const [clients, setClients] = useState<ClientRow[]>([]);
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [ledger, setLedger] = useState<LedgerEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingLedger, setLoadingLedger] = useState(false);

  const [payDialog, setPayDialog] = useState(false);
  const [payForm, setPayForm] = useState({ date: todayISO(), amount: '', notes: '' });

  const [valeDialog, setValeDialog] = useState(false);
  const [valeForm, setValeForm] = useState({
    date: todayISO(), description: '', amount: '', installments: '1',
  });

  // ===== Load all clients + balances =====
  const loadClients = useCallback(async () => {
    setLoading(true);
    const [clientsRes, txRes, weighRes] = await Promise.all([
      supabase.from('clients').select('id, name, nickname, document_number, phone, whatsapp').eq('status', 'ativo'),
      supabase.from('client_transactions').select('client_id, type, value, amount'),
      supabase.from('weighings').select('client_id, total_value, status'),
    ]);

    const list = clientsRes.data || [];
    const balances: Record<string, number> = {};
    list.forEach(c => { balances[c.id] = 0; });

    (weighRes.data || []).forEach(w => {
      if (w.status === 'cancelado') return;
      if (balances[w.client_id] === undefined) return;
      balances[w.client_id] += Number(w.total_value || 0);
    });

    (txRes.data || []).forEach(t => {
      if (balances[t.client_id] === undefined) return;
      const v = Number(t.value ?? t.amount ?? 0);
      // value semantics: vales => positivo (aumenta saldo a pagar)
      // pagamentos => negativo (reduz saldo) — armazenado já com sinal
      balances[t.client_id] += v;
    });

    const rows: ClientRow[] = list.map(c => ({
      id: c.id,
      name: c.name,
      nickname: c.nickname,
      document_number: c.document_number,
      balance: balances[c.id] || 0,
      phone: c.phone || null,
      whatsapp: c.whatsapp || null,
    }));

    rows.sort((a, b) => {
      // positivos (a pagar) primeiro, depois maior saldo
      if ((a.balance > 0) !== (b.balance > 0)) return a.balance > 0 ? -1 : 1;
      return b.balance - a.balance;
    });

    setClients(rows);
    setLoading(false);
  }, []);

  const { refresh, isRefreshing, lastRefreshAt } = useAutoRefresh(loadClients);

  // ===== Load ledger for selected client =====
  const loadLedger = useCallback(async (clientId: string) => {
    setLoadingLedger(true);
    const [weighRes, txRes] = await Promise.all([
      supabase.from('weighings')
        .select('id, created_at, material_type, final_net_weight, net_weight, price_per_kg, total_value, status, notes, ticket_number')
        .eq('client_id', clientId)
        .neq('status', 'cancelado')
        .order('created_at', { ascending: false }),
      supabase.from('client_transactions')
        .select('id, created_at, transaction_date, type, description, value, amount, mista_kg, pesada_kg, limaria_kg, fundido_kg, amortecedor_kg, total_kg, price_used')
        .eq('client_id', clientId)
        .order('created_at', { ascending: false }),
    ]);

    const entries: LedgerEntry[] = [];

    (weighRes.data || []).forEach(w => {
      const kg = Number(w.final_net_weight ?? w.net_weight ?? 0);
      const mat = (w.material_type || 'mista').toLowerCase();
      const e: LedgerEntry = {
        id: `w-${w.id}`,
        date: w.created_at,
        type: 'PESAGEM',
        mista_kg: 0, pesada_kg: 0, limaria_kg: 0, fundido_kg: 0, amortecedor_kg: 0,
        total_kg: kg,
        price: Number(w.price_per_kg || 0),
        value: Number(w.total_value || 0),
        transferred: 0,
        notes: `Ticket #${w.ticket_number}${w.notes ? ' — ' + w.notes : ''}`,
      };
      if (mat.includes('mista')) e.mista_kg = kg;
      else if (mat.includes('pesada')) e.pesada_kg = kg;
      else if (mat.includes('limaria')) e.limaria_kg = kg;
      else if (mat.includes('fundido')) e.fundido_kg = kg;
      else if (mat.includes('amorte')) e.amortecedor_kg = kg;
      else e.mista_kg = kg;
      entries.push(e);
    });

    (txRes.data || []).forEach(t => {
      const rawType = (t.type || '').toLowerCase();
      let entryType: LedgerEntry['type'] = 'VALE';
      if (rawType.includes('pagamento')) entryType = 'PAGAMENTO';
      else if (rawType.includes('acerto') || rawType.includes('settlement')) entryType = 'ACERTO';
      else if (rawType.includes('vale') || rawType.includes('debito')) entryType = 'VALE';

      const v = Number(t.value ?? t.amount ?? 0);
      entries.push({
        id: `t-${t.id}`,
        date: t.transaction_date || t.created_at,
        type: entryType,
        mista_kg: Number(t.mista_kg || 0),
        pesada_kg: Number(t.pesada_kg || 0),
        limaria_kg: Number(t.limaria_kg || 0),
        fundido_kg: Number(t.fundido_kg || 0),
        amortecedor_kg: Number(t.amortecedor_kg || 0),
        total_kg: Number(t.total_kg || 0),
        price: Number(t.price_used || 0),
        value: entryType === 'PAGAMENTO' ? 0 : Math.max(0, v),
        transferred: entryType === 'PAGAMENTO' ? Math.abs(v) : 0,
        notes: t.description || '',
      });
    });

    entries.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    setLedger(entries);
    setLoadingLedger(false);
  }, []);

  useEffect(() => {
    if (selectedId) loadLedger(selectedId);
    else setLedger([]);
  }, [selectedId, loadLedger]);

  // ===== Filters & summary =====
  const filteredClients = useMemo(() => {
    const s = search.trim().toLowerCase();
    if (!s) return clients;
    return clients.filter(c =>
      c.name.toLowerCase().includes(s) ||
      (c.nickname || '').toLowerCase().includes(s) ||
      c.document_number.includes(search.trim())
    );
  }, [clients, search]);

  const selectedClient = clients.find(c => c.id === selectedId) || null;

  const summary = useMemo(() => {
    const totalGenerated = ledger
      .filter(e => e.type === 'PESAGEM' || e.type === 'VALE')
      .reduce((s, e) => s + e.value, 0);
    const totalTransferred = ledger
      .filter(e => e.type === 'PAGAMENTO' || e.type === 'ACERTO')
      .reduce((s, e) => s + e.transferred, 0);
    const balance = totalGenerated - totalTransferred;
    const weighCount = ledger.filter(e => e.type === 'PESAGEM').length;
    return { totalGenerated, totalTransferred, balance, weighCount };
  }, [ledger]);

  // ===== Save handlers =====
  const handleSavePayment = async () => {
    if (!selectedId || !payForm.amount) {
      toast.error('Informe o valor'); return;
    }
    const v = parseFloat(payForm.amount);
    if (!v || v <= 0) { toast.error('Valor inválido'); return; }

    const { error } = await supabase.from('client_transactions').insert({
      client_id: selectedId,
      type: 'pagamento',
      description: payForm.notes || 'Pagamento ao cliente',
      amount: v,
      value: -v, // negativo reduz o saldo a pagar
      transaction_date: payForm.date,
      created_by: user?.id,
      status: 'aberto',
    });
    if (error) { toast.error(error.message); return; }
    toast.success('Pagamento registrado!');
    setPayDialog(false);
    setPayForm({ date: todayISO(), amount: '', notes: '' });
    await Promise.all([loadClients(), loadLedger(selectedId)]);
  };

  const handleSaveVale = async (): Promise<void> => {
    if (!selectedId || !valeForm.amount || !valeForm.description) {
      toast.error('Preencha descrição e valor'); return;
    }
    const total = parseFloat(valeForm.amount);
    const n = Math.max(1, Math.min(12, parseInt(valeForm.installments || '1') || 1));
    if (!total || total <= 0) { toast.error('Valor inválido'); return; }

    const each = +(total / n).toFixed(2);
    const rows = Array.from({ length: n }).map((_, i) => ({
      client_id: selectedId,
      type: 'vale',
      description: n > 1 ? `PARCELA ${i + 1} de ${n} - ${valeForm.description}` : valeForm.description,
      amount: each,
      value: each, // positivo: aumenta o que devemos ao cliente? Não. VALE = adiantamento que cliente recebeu, REDUZ o saldo a pagar.
      transaction_date: valeForm.date,
      created_by: user?.id,
      status: 'aberto',
    }));

    // Vale = adiantamento dado ao cliente => reduz saldo a pagar => value negativo
    rows.forEach(r => { r.value = -each; });

    try {
      const { error } = await supabase.from('client_transactions').insert(rows);
      if (error) {
        console.error('Erro ao salvar vale:', error);
        toast.error(error.message);
        return;
      }
      toast.success(n > 1 ? `${n} parcelas registradas!` : 'Vale registrado!');
      setValeDialog(false);
      setValeForm({ date: todayISO(), description: '', amount: '', installments: '1' });
      await Promise.all([loadClients(), loadLedger(selectedId)]);
    } catch (err: any) {
      console.error('Erro inesperado ao salvar vale:', err);
      toast.error(err?.message || 'Erro inesperado ao salvar');
    }
  };

  // ===== CSV export =====
  const exportCSV = () => {
    if (!selectedClient) return;
    const headers = ['Data','Tipo','Mista(kg)','Pesada(kg)','Limaria(kg)','Fundido(kg)','Amortec.(kg)','Total kg','Preço R$/kg','Valor R$','Transferido R$','Diferença R$','OBS'];
    const lines = [headers.join(';')];
    ledger.forEach(e => {
      const diff = e.value - e.transferred;
      lines.push([
        fmtDate(e.date), e.type,
        num(e.mista_kg, 1), num(e.pesada_kg, 1), num(e.limaria_kg, 1),
        num(e.fundido_kg, 1), num(e.amortecedor_kg, 1), num(e.total_kg, 1),
        num(e.price), num(e.value), num(e.transferred), num(diff),
        (e.notes || '').replace(/;/g, ','),
      ].join(';'));
    });
    const blob = new Blob(['\uFEFF' + lines.join('\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `extrato_${selectedClient.name.replace(/\s+/g, '_')}_${todayISO()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ===== WhatsApp =====
  const sendWhatsApp = () => {
    if (!selectedClient) return;
    const phone = (selectedClient.whatsapp || selectedClient.phone || '').replace(/\D/g, '');
    if (!phone) { toast.error('Cliente sem telefone cadastrado'); return; }
    const fullPhone = phone.length <= 11 ? `55${phone}` : phone;

    const lines: string[] = [
      '📊 *Extrato Sucata União*',
      `Cliente: ${selectedClient.name}`,
      `Data: ${fmtDate(new Date().toISOString())}`,
      '─────────────────',
    ];
    ledger.forEach(e => {
      const val = e.type === 'PAGAMENTO' ? -e.transferred : e.value;
      lines.push(`${fmtDate(e.date)} | ${e.type} | ${money(val)}`);
    });
    lines.push('─────────────────');
    lines.push(`Saldo atual: ${money(summary.balance)}`);
    lines.push('Dúvidas? (31) 99653-5321');

    const msg = encodeURIComponent(lines.join('\n'));
    window.open(`https://wa.me/${fullPhone}?text=${msg}`, '_blank');
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold">Conta Corrente</h1>
          <p className="text-sm text-muted-foreground">Controle financeiro por cliente</p>
        </div>
        <RefreshButton onRefresh={refresh} isRefreshing={isRefreshing} lastRefreshAt={lastRefreshAt} />
      </div>

      <Tabs defaultValue="por-cliente" className="w-full">
        <TabsList>
          <TabsTrigger value="por-cliente">Por Cliente</TabsTrigger>
          <TabsTrigger value="avulsos">Avulsos</TabsTrigger>
        </TabsList>
        <TabsContent value="por-cliente">
        <div className="grid grid-cols-12 gap-3" style={{ minHeight: 'calc(100vh - 220px)' }}>
        {/* ===== LEFT PANEL ===== */}
        <Card className="col-span-12 lg:col-span-4 xl:col-span-3 flex flex-col">
          <CardContent className="p-3 flex-1 flex flex-col gap-2 min-h-0">
            <div className="relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
              <Input
                value={search}
                onChange={e => setSearch(e.target.value)}
                placeholder="Buscar por nome ou apelido..."
                className="pl-8 h-8 text-xs"
              />
            </div>
            <div className="flex-1 overflow-auto -mx-3 px-1">
              {loading ? (
                <div className="text-center text-xs text-muted-foreground py-6">Carregando...</div>
              ) : filteredClients.length === 0 ? (
                <div className="text-center text-xs text-muted-foreground py-6">Nenhum cliente</div>
              ) : filteredClients.map(c => {
                const aPagar = c.balance > 0;
                const isDevedor = c.balance < 0;
                const isSel = c.id === selectedId;
                return (
                  <button
                    key={c.id}
                    onClick={() => setSelectedId(c.id)}
                    className={`w-full text-left px-2 py-2 rounded mb-1 border transition ${
                      isSel ? 'bg-primary/10 border-primary' : 'border-transparent hover:bg-secondary'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-medium truncate">{c.nickname || c.name}</div>
                        {c.nickname && <div className="text-[10px] text-muted-foreground truncate">{c.name}</div>}
                      </div>
                      <div className={`text-xs font-mono font-semibold ${aPagar ? 'text-red-600' : isDevedor ? 'text-green-600' : 'text-muted-foreground'}`}>
                        {money(c.balance)}
                      </div>
                    </div>
                    <div className="mt-1">
                      {aPagar ? (
                        <Badge className="text-[9px] bg-red-100 text-red-700 border border-red-300 hover:bg-red-100">AGUARDANDO PAGAMENTO</Badge>
                      ) : isDevedor ? (
                        <Badge className="text-[9px] bg-green-100 text-green-700 border border-green-300 hover:bg-green-100">DEVEDOR</Badge>
                      ) : null}
                    </div>
                  </button>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* ===== RIGHT PANEL ===== */}
        <div className="col-span-12 lg:col-span-8 xl:col-span-9 flex flex-col gap-3 min-h-0">
          {!selectedClient ? (
            <Card className="flex-1 flex items-center justify-center">
              <CardContent className="text-center text-muted-foreground text-sm py-12">
                Selecione um cliente para ver o extrato
              </CardContent>
            </Card>
          ) : (
            <>
              {/* Header + actions */}
              <div className="flex items-center justify-between flex-wrap gap-2">
                <div>
                  <div className="text-base font-semibold">{selectedClient.name}</div>
                  <div className="text-[10px] text-muted-foreground">
                    {selectedClient.document_number}{selectedClient.nickname ? ` • ${selectedClient.nickname}` : ''}
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button size="sm" variant="outline" onClick={exportCSV}>
                    <Download className="h-3.5 w-3.5 mr-1" /> Exportar Extrato
                  </Button>
                  <Button size="sm" variant="outline" onClick={sendWhatsApp}>
                    <MessageCircle className="h-3.5 w-3.5 mr-1" /> Enviar WhatsApp
                  </Button>
                  <Button size="sm" className="bg-accent text-accent-foreground hover:bg-accent/90" onClick={() => setPayDialog(true)}>
                    <DollarSign className="h-3.5 w-3.5 mr-1" /> Registrar Pagamento
                  </Button>
                  <Button size="sm" className="bg-warning text-warning-foreground hover:bg-warning/90" onClick={() => setValeDialog(true)}>
                    <Plus className="h-3.5 w-3.5 mr-1" /> Lançar Vale/Débito
                  </Button>
                </div>
              </div>

              {/* Summary cards */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">
                <Card><CardContent className="p-3 flex items-center gap-2">
                  <Receipt className="h-7 w-7 text-primary" />
                  <div>
                    <p className="text-base font-bold">{money(summary.totalGenerated)}</p>
                    <p className="text-[10px] text-muted-foreground">Gerado por Pesagens/Vales</p>
                  </div>
                </CardContent></Card>
                <Card><CardContent className="p-3 flex items-center gap-2">
                  <Wallet className="h-7 w-7 text-accent" />
                  <div>
                    <p className="text-base font-bold">{money(summary.totalTransferred)}</p>
                    <p className="text-[10px] text-muted-foreground">Total Transferido</p>
                  </div>
                </CardContent></Card>
                <Card><CardContent className="p-3 flex items-center gap-2">
                  <DollarSign className={`h-7 w-7 ${summary.balance > 0 ? 'text-red-600' : summary.balance < 0 ? 'text-green-600' : 'text-muted-foreground'}`} />
                  <div>
                    <p className={`text-base font-bold ${summary.balance > 0 ? 'text-red-600' : summary.balance < 0 ? 'text-green-600' : ''}`}>
                      {money(summary.balance)}
                    </p>
                    <p className="text-[10px] text-muted-foreground">
                      Saldo Atual {summary.balance > 0 ? '(Aguardando pagamento)' : summary.balance < 0 ? '(Devedor)' : ''}
                    </p>
                  </div>
                </CardContent></Card>
                <Card><CardContent className="p-3 flex items-center gap-2">
                  <div className="h-7 w-7 rounded bg-primary/10 flex items-center justify-center text-primary text-xs font-bold">
                    {summary.weighCount}
                  </div>
                  <div>
                    <p className="text-base font-bold">{summary.weighCount}</p>
                    <p className="text-[10px] text-muted-foreground">Pesagens</p>
                  </div>
                </CardContent></Card>
              </div>

              {/* Ledger table */}
              <div className="bg-card rounded border overflow-auto flex-1 min-h-[300px]">
                <table className="w-full table-dense text-[11px]">
                  <thead className="sticky top-0 bg-secondary z-10">
                    <tr className="border-b">
                      <th className="text-left text-muted-foreground font-medium">Data</th>
                      <th className="text-left text-muted-foreground font-medium">Tipo</th>
                      <th className="text-right text-muted-foreground font-medium">Mista</th>
                      <th className="text-right text-muted-foreground font-medium">Pesada</th>
                      <th className="text-right text-muted-foreground font-medium">Limaria</th>
                      <th className="text-right text-muted-foreground font-medium">Fundido</th>
                      <th className="text-right text-muted-foreground font-medium">Amortec.</th>
                      <th className="text-right text-muted-foreground font-medium">Total kg</th>
                      <th className="text-right text-muted-foreground font-medium">R$/kg</th>
                      <th className="text-right text-muted-foreground font-medium">Valor R$</th>
                      <th className="text-right text-muted-foreground font-medium">Transferido</th>
                      <th className="text-right text-muted-foreground font-medium">Diferença</th>
                      <th className="text-left text-muted-foreground font-medium">OBS</th>
                    </tr>
                  </thead>
                  <tbody>
                    {loadingLedger ? (
                      <tr><td colSpan={13} className="text-center py-8 text-muted-foreground">Carregando extrato...</td></tr>
                    ) : ledger.length === 0 ? (
                      <tr><td colSpan={13} className="text-center py-8 text-muted-foreground">Sem lançamentos</td></tr>
                    ) : ledger.map(e => {
                      const diff = e.value - e.transferred;
                      return (
                        <tr key={e.id} className={`border-b border-border/50 ${typeBg[e.type]}`}>
                          <td className="whitespace-nowrap">{fmtDate(e.date)}</td>
                          <td className="font-semibold">{e.type}</td>
                          <td className="text-right font-mono">{e.mista_kg ? num(e.mista_kg, 1) : '—'}</td>
                          <td className="text-right font-mono">{e.pesada_kg ? num(e.pesada_kg, 1) : '—'}</td>
                          <td className="text-right font-mono">{e.limaria_kg ? num(e.limaria_kg, 1) : '—'}</td>
                          <td className="text-right font-mono">{e.fundido_kg ? num(e.fundido_kg, 1) : '—'}</td>
                          <td className="text-right font-mono">{e.amortecedor_kg ? num(e.amortecedor_kg, 1) : '—'}</td>
                          <td className="text-right font-mono font-semibold">{e.total_kg ? num(e.total_kg, 1) : '—'}</td>
                          <td className="text-right font-mono">{e.price ? num(e.price) : '—'}</td>
                          <td className="text-right font-mono text-primary">{e.value ? money(e.value) : '—'}</td>
                          <td className="text-right font-mono text-accent">{e.transferred ? money(e.transferred) : '—'}</td>
                          <td className={`text-right font-mono ${diff > 0 ? 'text-destructive' : diff < 0 ? 'text-accent' : ''}`}>
                            {diff !== 0 ? money(diff) : '—'}
                          </td>
                          <td className="max-w-[200px] truncate" title={e.notes}>{e.notes}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      </div>
      </TabsContent>
      <TabsContent value="avulsos">
        <AvulsosTab />
      </TabsContent>
      </Tabs>

      {/* ===== Modal: Registrar Pagamento ===== */}
      <Dialog open={payDialog} onOpenChange={setPayDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>Registrar Pagamento</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div>
              <Label className="text-xs">Data</Label>
              <Input type="date" value={payForm.date} onChange={e => setPayForm(p => ({ ...p, date: e.target.value }))} className="h-8 text-xs" />
            </div>
            <div>
              <Label className="text-xs">Valor Transferido (R$)</Label>
              <Input type="number" step="0.01" value={payForm.amount} onChange={e => setPayForm(p => ({ ...p, amount: e.target.value }))} className="h-8 text-xs" />
            </div>
            <div>
              <Label className="text-xs">Observação</Label>
              <Textarea value={payForm.notes} onChange={e => setPayForm(p => ({ ...p, notes: e.target.value }))} className="text-xs min-h-[60px]" placeholder="PIX, transferência..." />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" size="sm" onClick={() => setPayDialog(false)}>Cancelar</Button>
              <Button size="sm" className="bg-accent text-accent-foreground hover:bg-accent/90" onClick={handleSavePayment}>Confirmar</Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* ===== Modal: Vale/Débito ===== */}
      <Dialog open={valeDialog} onOpenChange={setValeDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>Lançar Vale / Débito</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div>
              <Label className="text-xs">Data</Label>
              <Input type="date" value={valeForm.date} onChange={e => setValeForm(p => ({ ...p, date: e.target.value }))} className="h-8 text-xs" />
            </div>
            <div>
              <Label className="text-xs">Descrição</Label>
              <Input value={valeForm.description} onChange={e => setValeForm(p => ({ ...p, description: e.target.value }))} className="h-8 text-xs" placeholder="Ex: Pneus, Adiantamento" />
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <Label className="text-xs">Valor Total (R$)</Label>
                <Input type="number" step="0.01" value={valeForm.amount} onChange={e => setValeForm(p => ({ ...p, amount: e.target.value }))} className="h-8 text-xs" />
              </div>
              <div>
                <Label className="text-xs">Parcelas</Label>
                <Select defaultValue="1" value={valeForm.installments || '1'} onValueChange={v => { if (v) setValeForm(p => ({ ...p, installments: v })); }}>
                  <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="1x" /></SelectTrigger>
                  <SelectContent>
                    {Array.from({ length: 12 }).map((_, i) => (
                      <SelectItem key={i + 1} value={String(i + 1)}>{i + 1}x</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" size="sm" onClick={() => setValeDialog(false)}>Cancelar</Button>
              <Button size="sm" className="bg-warning text-warning-foreground hover:bg-warning/90" onClick={handleSaveVale}>Confirmar</Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
